spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yellowpal/spring-cloud-config.git
          basedir: target/config
          username:
          password:
  rabbitmq:
    host: 192.168.43.90
    port: 5672
    username: Yellow
    password: pal
logging:
  level:
    org.springframework.*: info
# 刷新配置到client端 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
