#server:
#  port: 8762
eureka:
#  instance:
#    hostname: 127.0.0.1
  client:
    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: server