spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#ribbon 负载均衡策略配置，服务名.ribbon.NFLoadBalancerRuleClassName
TEST:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule